### ISSUE TITLE
Support for Vector Processor (RVV 1.0)

### ISSUE THREAD

**Issue by Tameem-10xE** [ryan4yin/nixos-licheepi4a#10]
Hi, Is this OS has support for RVV 1.0 or in other words I can compile the code for vector extension using the risc-v toolchain compiler available in it?

Thank you

**Comment by ryan4yin** [comment]
TH1520 only has its "THead extension", the RVV 0.7.1 draft.
the official GCC toolchain do not support this extension, so this flake do not have support for it too.

As for  RVV1.0, just use a GCC toolchain(the latest version of gcc13 maybe?) that supports RVV1.0 and the system will support it.

**Comment by Tameem-10xE** [comment]
Thanks for the clarification regarding TH1520 and RVV support. 

So, that meant, currently no commercial hardware is available with rvv 1.0 and as of for risc-v toolchain gcc, it has vector rvv 1.0 available, I am already using gcc 13.2 (ubuntu glibc 22.04) for cross compiling rvv 1.0 and running it on qemu-riscv

Thank you
