### ISSUE TITLE
Use T-Head optimized toolchain for compilation

### ISSUE THREAD

**Issue by Kreyren** [ryan4yin/nixos-licheepi4a#14]
Currently the LicheePi 4A requires the optimized toolchain from T-Head as it fixes lots of issues such as audio popping and overall efficiency [https://github.com/armbian/build/pull/5689#issuecomment-1712415913]

Referencing https://github.com/armbian/build/issues/5692

Proposing to implement it.

**Comment by ryan4yin** [comment]
This is difficult to implement. NixOS's gcc toolchain contains a lot of customization and encapsulation, and adapting t-head 's optimization gcc toolchain to this pile of things will be a huge project.

**Comment by Kreyren** [comment]
> This is difficult to implement. NixOS's gcc toolchain contains a lot of customization and encapsulation, and adapting t-head 's optimization gcc toolchain to this pile of things will be a huge project. -- @ryan4yin

Afaik the optimized toolchain is GCC so we can just grab the patches from:

https://github.com/riscv-collab/riscv-gnu-toolchain/compare/master...revyos:revyos-gnu-toolchain:thead-toolchains

and apply them on top of nix's gcc or use these sources for the nix's packages?

CC @chainsx @Rabenda can you confirm that these patches are enough?

**Comment by RevySR** [comment]
Using the T-Head toolchain is risky and causes bugs that need to be resolved on your own.

**Comment by Kreyren** [comment]
> Using the T-Head toolchain is risky and causes bugs that need to be resolved on your own. -- @Rabenda (https://github.com/ryan4yin/nixos-licheepi4a/issues/14#issuecomment-1716080882)

Can you elaborate on what kind of bugs or can you recommend patches/provide context to address the popping audio issue? As that's currently the main problem on my end

**Comment by RevySR** [comment]
> > Using the T-Head toolchain is risky and causes bugs that need to be resolved on your own. -- @Rabenda ([#14 (comment)](https://github.com/ryan4yin/nixos-licheepi4a/issues/14#issuecomment-1716080882))
> 
> Can you elaborate on what kind of bugs or can you recommend patches/provide context to address the popping audio issue? As that's currently the main problem on my end

1. https://github.com/T-head-Semi/gcc/issues
2. It doesn't fix any audio issues
